[project]
name = "mcpdemo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13.9"
dependencies = [
    "fastmcp>=2.14.3",
    "python-dotenv>=1.2.1",
]

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["src"]
